name: BlockStock
main: me.mjkaufer.BlockStock.BlockStock
version: 1.0
author: mjkaufer
commands:
    blockstock:
        description: Converts items into blocks.
        aliases: [bs]
        permission: BlockStock.block
        usage: |
            /<blockstock> [id] [blocks]
            Example: /<blockstock> - Converts as many as possible of the currently highlighted inventory item into blocks.
            Example: /<blockstock> 4 - Converts four of the currently highlighted inventory item into blocks.
            Example: /<blockstock> 4 REDSTONE - Converts redstone in your inventory into 4 redstone blocks, if possible. 
permissions:
    BlockStock.block:
        description: Allows use of /blockstock
        default: true